from typing import TYPE_CHECKING, Protocol, Self, runtime_checkable

if TYPE_CHECKING:
    from collections.abc import Iterable

__all__ = ["Ring", "SupportsKeysAndGetitem"]


@runtime_checkable
class SupportsKeysAndGetitem[K, V](Protocol):
    def keys(self) -> Iterable[K]: ...
    def __getitem__(self, key: K, /) -> V: ...


@runtime_checkable
class Ring(Protocol):
    def __add__(self, value: Self, /) -> Self: ...
    def __radd__(self, value: Self, /) -> Self: ...
    def __mul__(self, value: Self, /) -> Self: ...
    def __rmul__(self, value: Self, /) -> Self: ...
    def __neg__(self) -> Self: ...
